FROM golang:1.24-alpine

RUN apk add --no-cache git
RUN go install github.com/air-verse/air@v1.61.7
RUN go install github.com/pressly/goose/v3/cmd/goose@v3.24.1
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.28.0

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080
CMD ["air"]
