// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_logs
`

func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (actor_id, action, object_type, object_id, meta)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, actor_id, action, object_type, object_id, meta, created_at
`

type CreateAuditLogParams struct {
	ActorID    pgtype.Int8 `json:"actor_id"`
	Action     string      `json:"action"`
	ObjectType pgtype.Text `json:"object_type"`
	ObjectID   pgtype.Text `json:"object_id"`
	Meta       []byte      `json:"meta"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorID,
		arg.Action,
		arg.ObjectType,
		arg.ObjectID,
		arg.Meta,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.ObjectType,
		&i.ObjectID,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT al.id, al.actor_id, al.action, al.object_type, al.object_id, al.meta, al.created_at, u.username as actor_username
FROM audit_logs al
LEFT JOIN users u ON u.id = al.actor_id
ORDER BY al.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAuditLogsRow struct {
	ID            int64              `json:"id"`
	ActorID       pgtype.Int8        `json:"actor_id"`
	Action        string             `json:"action"`
	ObjectType    pgtype.Text        `json:"object_type"`
	ObjectID      pgtype.Text        `json:"object_id"`
	Meta          []byte             `json:"meta"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ActorUsername pgtype.Text        `json:"actor_username"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.ObjectType,
			&i.ObjectID,
			&i.Meta,
			&i.CreatedAt,
			&i.ActorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByAction = `-- name: ListAuditLogsByAction :many
SELECT al.id, al.actor_id, al.action, al.object_type, al.object_id, al.meta, al.created_at, u.username as actor_username
FROM audit_logs al
LEFT JOIN users u ON u.id = al.actor_id
WHERE al.action = $1
ORDER BY al.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByActionParams struct {
	Action string `json:"action"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListAuditLogsByActionRow struct {
	ID            int64              `json:"id"`
	ActorID       pgtype.Int8        `json:"actor_id"`
	Action        string             `json:"action"`
	ObjectType    pgtype.Text        `json:"object_type"`
	ObjectID      pgtype.Text        `json:"object_id"`
	Meta          []byte             `json:"meta"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ActorUsername pgtype.Text        `json:"actor_username"`
}

func (q *Queries) ListAuditLogsByAction(ctx context.Context, arg ListAuditLogsByActionParams) ([]ListAuditLogsByActionRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByAction, arg.Action, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsByActionRow{}
	for rows.Next() {
		var i ListAuditLogsByActionRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.ObjectType,
			&i.ObjectID,
			&i.Meta,
			&i.CreatedAt,
			&i.ActorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByActor = `-- name: ListAuditLogsByActor :many
SELECT al.id, al.actor_id, al.action, al.object_type, al.object_id, al.meta, al.created_at, u.username as actor_username
FROM audit_logs al
LEFT JOIN users u ON u.id = al.actor_id
WHERE al.actor_id = $1
ORDER BY al.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByActorParams struct {
	ActorID pgtype.Int8 `json:"actor_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListAuditLogsByActorRow struct {
	ID            int64              `json:"id"`
	ActorID       pgtype.Int8        `json:"actor_id"`
	Action        string             `json:"action"`
	ObjectType    pgtype.Text        `json:"object_type"`
	ObjectID      pgtype.Text        `json:"object_id"`
	Meta          []byte             `json:"meta"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ActorUsername pgtype.Text        `json:"actor_username"`
}

func (q *Queries) ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]ListAuditLogsByActorRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByActor, arg.ActorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsByActorRow{}
	for rows.Next() {
		var i ListAuditLogsByActorRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.ObjectType,
			&i.ObjectID,
			&i.Meta,
			&i.CreatedAt,
			&i.ActorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByObject = `-- name: ListAuditLogsByObject :many
SELECT al.id, al.actor_id, al.action, al.object_type, al.object_id, al.meta, al.created_at, u.username as actor_username
FROM audit_logs al
LEFT JOIN users u ON u.id = al.actor_id
WHERE al.object_type = $1 AND al.object_id = $2
ORDER BY al.created_at DESC
LIMIT $3 OFFSET $4
`

type ListAuditLogsByObjectParams struct {
	ObjectType pgtype.Text `json:"object_type"`
	ObjectID   pgtype.Text `json:"object_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListAuditLogsByObjectRow struct {
	ID            int64              `json:"id"`
	ActorID       pgtype.Int8        `json:"actor_id"`
	Action        string             `json:"action"`
	ObjectType    pgtype.Text        `json:"object_type"`
	ObjectID      pgtype.Text        `json:"object_id"`
	Meta          []byte             `json:"meta"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ActorUsername pgtype.Text        `json:"actor_username"`
}

func (q *Queries) ListAuditLogsByObject(ctx context.Context, arg ListAuditLogsByObjectParams) ([]ListAuditLogsByObjectRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByObject,
		arg.ObjectType,
		arg.ObjectID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsByObjectRow{}
	for rows.Next() {
		var i ListAuditLogsByObjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.ObjectType,
			&i.ObjectID,
			&i.Meta,
			&i.CreatedAt,
			&i.ActorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
