// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: batches.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countParticipantRowsByBatch = `-- name: CountParticipantRowsByBatch :one
SELECT count(*) FROM participant_rows WHERE batch_id = $1
`

func (q *Queries) CountParticipantRowsByBatch(ctx context.Context, batchID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countParticipantRowsByBatch, batchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImportBatch = `-- name: CreateImportBatch :one
INSERT INTO import_batches (event_id, file_path, status, rows_total, tokens)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, event_id, file_path, status, rows_total, rows_ok, rows_failed, mapping, tokens, report, created_at, updated_at
`

type CreateImportBatchParams struct {
	EventID   int64       `json:"event_id"`
	FilePath  string      `json:"file_path"`
	Status    pgtype.Text `json:"status"`
	RowsTotal pgtype.Int4 `json:"rows_total"`
	Tokens    []byte      `json:"tokens"`
}

func (q *Queries) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, createImportBatch,
		arg.EventID,
		arg.FilePath,
		arg.Status,
		arg.RowsTotal,
		arg.Tokens,
	)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.FilePath,
		&i.Status,
		&i.RowsTotal,
		&i.RowsOk,
		&i.RowsFailed,
		&i.Mapping,
		&i.Tokens,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createParticipantRow = `-- name: CreateParticipantRow :one
INSERT INTO participant_rows (batch_id, iin, name, payload, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, batch_id, iin, name, payload, status, error, created_at
`

type CreateParticipantRowParams struct {
	BatchID int64       `json:"batch_id"`
	Iin     pgtype.Text `json:"iin"`
	Name    pgtype.Text `json:"name"`
	Payload []byte      `json:"payload"`
	Status  pgtype.Text `json:"status"`
}

func (q *Queries) CreateParticipantRow(ctx context.Context, arg CreateParticipantRowParams) (ParticipantRow, error) {
	row := q.db.QueryRow(ctx, createParticipantRow,
		arg.BatchID,
		arg.Iin,
		arg.Name,
		arg.Payload,
		arg.Status,
	)
	var i ParticipantRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Iin,
		&i.Name,
		&i.Payload,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const deleteImportBatch = `-- name: DeleteImportBatch :exec
DELETE FROM import_batches WHERE id = $1
`

func (q *Queries) DeleteImportBatch(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteImportBatch, id)
	return err
}

const getImportBatchByID = `-- name: GetImportBatchByID :one
SELECT id, event_id, file_path, status, rows_total, rows_ok, rows_failed, mapping, tokens, report, created_at, updated_at FROM import_batches WHERE id = $1
`

func (q *Queries) GetImportBatchByID(ctx context.Context, id int64) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, getImportBatchByID, id)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.FilePath,
		&i.Status,
		&i.RowsTotal,
		&i.RowsOk,
		&i.RowsFailed,
		&i.Mapping,
		&i.Tokens,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listImportBatchesByEvent = `-- name: ListImportBatchesByEvent :many
SELECT id, event_id, file_path, status, rows_total, rows_ok, rows_failed, mapping, tokens, report, created_at, updated_at FROM import_batches
WHERE event_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListImportBatchesByEvent(ctx context.Context, eventID int64) ([]ImportBatch, error) {
	rows, err := q.db.Query(ctx, listImportBatchesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportBatch{}
	for rows.Next() {
		var i ImportBatch
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.FilePath,
			&i.Status,
			&i.RowsTotal,
			&i.RowsOk,
			&i.RowsFailed,
			&i.Mapping,
			&i.Tokens,
			&i.Report,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantRowsByBatch = `-- name: ListParticipantRowsByBatch :many
SELECT id, batch_id, iin, name, payload, status, error, created_at FROM participant_rows
WHERE batch_id = $1
ORDER BY id
`

func (q *Queries) ListParticipantRowsByBatch(ctx context.Context, batchID int64) ([]ParticipantRow, error) {
	rows, err := q.db.Query(ctx, listParticipantRowsByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParticipantRow{}
	for rows.Next() {
		var i ParticipantRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.Iin,
			&i.Name,
			&i.Payload,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImportBatchMapping = `-- name: UpdateImportBatchMapping :one
UPDATE import_batches
SET mapping = $2, status = $3, updated_at = now()
WHERE id = $1
RETURNING id, event_id, file_path, status, rows_total, rows_ok, rows_failed, mapping, tokens, report, created_at, updated_at
`

type UpdateImportBatchMappingParams struct {
	ID      int64       `json:"id"`
	Mapping []byte      `json:"mapping"`
	Status  pgtype.Text `json:"status"`
}

func (q *Queries) UpdateImportBatchMapping(ctx context.Context, arg UpdateImportBatchMappingParams) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, updateImportBatchMapping, arg.ID, arg.Mapping, arg.Status)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.FilePath,
		&i.Status,
		&i.RowsTotal,
		&i.RowsOk,
		&i.RowsFailed,
		&i.Mapping,
		&i.Tokens,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateImportBatchStatus = `-- name: UpdateImportBatchStatus :one
UPDATE import_batches
SET status = $2, rows_ok = $3, rows_failed = $4, report = $5, updated_at = now()
WHERE id = $1
RETURNING id, event_id, file_path, status, rows_total, rows_ok, rows_failed, mapping, tokens, report, created_at, updated_at
`

type UpdateImportBatchStatusParams struct {
	ID         int64       `json:"id"`
	Status     pgtype.Text `json:"status"`
	RowsOk     pgtype.Int4 `json:"rows_ok"`
	RowsFailed pgtype.Int4 `json:"rows_failed"`
	Report     []byte      `json:"report"`
}

func (q *Queries) UpdateImportBatchStatus(ctx context.Context, arg UpdateImportBatchStatusParams) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, updateImportBatchStatus,
		arg.ID,
		arg.Status,
		arg.RowsOk,
		arg.RowsFailed,
		arg.Report,
	)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.FilePath,
		&i.Status,
		&i.RowsTotal,
		&i.RowsOk,
		&i.RowsFailed,
		&i.Mapping,
		&i.Tokens,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateParticipantRowStatus = `-- name: UpdateParticipantRowStatus :exec
UPDATE participant_rows
SET status = $2, error = $3
WHERE id = $1
`

type UpdateParticipantRowStatusParams struct {
	ID     int64       `json:"id"`
	Status pgtype.Text `json:"status"`
	Error  pgtype.Text `json:"error"`
}

func (q *Queries) UpdateParticipantRowStatus(ctx context.Context, arg UpdateParticipantRowStatusParams) error {
	_, err := q.db.Exec(ctx, updateParticipantRowStatus, arg.ID, arg.Status, arg.Error)
	return err
}
