// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: certificates.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllCertificates = `-- name: CountAllCertificates :one
SELECT count(*) FROM certificates
`

func (q *Queries) CountAllCertificates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllCertificates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCertificatesByEvent = `-- name: CountCertificatesByEvent :one
SELECT count(*) FROM certificates WHERE event_id = $1
`

func (q *Queries) CountCertificatesByEvent(ctx context.Context, eventID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCertificatesByEvent, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCertificatesByOrganization = `-- name: CountCertificatesByOrganization :one
SELECT count(*) FROM certificates WHERE organization_id = $1
`

func (q *Queries) CountCertificatesByOrganization(ctx context.Context, organizationID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countCertificatesByOrganization, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCertificate = `-- name: CreateCertificate :one
INSERT INTO certificates (event_id, organization_id, iin, name, code, pdf_path, status, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, event_id, organization_id, iin, name, code, pdf_path, status, revoked_reason, payload, created_at, updated_at
`

type CreateCertificateParams struct {
	EventID        int64       `json:"event_id"`
	OrganizationID pgtype.Int8 `json:"organization_id"`
	Iin            pgtype.Text `json:"iin"`
	Name           pgtype.Text `json:"name"`
	Code           string      `json:"code"`
	PdfPath        pgtype.Text `json:"pdf_path"`
	Status         pgtype.Text `json:"status"`
	Payload        []byte      `json:"payload"`
}

func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, createCertificate,
		arg.EventID,
		arg.OrganizationID,
		arg.Iin,
		arg.Name,
		arg.Code,
		arg.PdfPath,
		arg.Status,
		arg.Payload,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.OrganizationID,
		&i.Iin,
		&i.Name,
		&i.Code,
		&i.PdfPath,
		&i.Status,
		&i.RevokedReason,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCertificate = `-- name: DeleteCertificate :exec
DELETE FROM certificates WHERE id = $1
`

func (q *Queries) DeleteCertificate(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCertificate, id)
	return err
}

const getCertificateByCode = `-- name: GetCertificateByCode :one
SELECT id, event_id, organization_id, iin, name, code, pdf_path, status, revoked_reason, payload, created_at, updated_at FROM certificates WHERE code = $1
`

func (q *Queries) GetCertificateByCode(ctx context.Context, code string) (Certificate, error) {
	row := q.db.QueryRow(ctx, getCertificateByCode, code)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.OrganizationID,
		&i.Iin,
		&i.Name,
		&i.Code,
		&i.PdfPath,
		&i.Status,
		&i.RevokedReason,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCertificateByCodeWithDetails = `-- name: GetCertificateByCodeWithDetails :one
SELECT c.id, c.event_id, c.organization_id, c.iin, c.name, c.code, c.pdf_path, c.status, c.revoked_reason, c.payload, c.created_at, c.updated_at, e.title as event_title, o.name as org_name
FROM certificates c
JOIN events e ON e.id = c.event_id
LEFT JOIN organizations o ON o.id = c.organization_id
WHERE c.code = $1
`

type GetCertificateByCodeWithDetailsRow struct {
	ID             int64              `json:"id"`
	EventID        int64              `json:"event_id"`
	OrganizationID pgtype.Int8        `json:"organization_id"`
	Iin            pgtype.Text        `json:"iin"`
	Name           pgtype.Text        `json:"name"`
	Code           string             `json:"code"`
	PdfPath        pgtype.Text        `json:"pdf_path"`
	Status         pgtype.Text        `json:"status"`
	RevokedReason  pgtype.Text        `json:"revoked_reason"`
	Payload        []byte             `json:"payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	EventTitle     string             `json:"event_title"`
	OrgName        pgtype.Text        `json:"org_name"`
}

func (q *Queries) GetCertificateByCodeWithDetails(ctx context.Context, code string) (GetCertificateByCodeWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getCertificateByCodeWithDetails, code)
	var i GetCertificateByCodeWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.OrganizationID,
		&i.Iin,
		&i.Name,
		&i.Code,
		&i.PdfPath,
		&i.Status,
		&i.RevokedReason,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventTitle,
		&i.OrgName,
	)
	return i, err
}

const getCertificateByID = `-- name: GetCertificateByID :one
SELECT id, event_id, organization_id, iin, name, code, pdf_path, status, revoked_reason, payload, created_at, updated_at FROM certificates WHERE id = $1
`

func (q *Queries) GetCertificateByID(ctx context.Context, id int64) (Certificate, error) {
	row := q.db.QueryRow(ctx, getCertificateByID, id)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.OrganizationID,
		&i.Iin,
		&i.Name,
		&i.Code,
		&i.PdfPath,
		&i.Status,
		&i.RevokedReason,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllCertificates = `-- name: ListAllCertificates :many
SELECT id, event_id, organization_id, iin, name, code, pdf_path, status, revoked_reason, payload, created_at, updated_at FROM certificates
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllCertificatesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllCertificates(ctx context.Context, arg ListAllCertificatesParams) ([]Certificate, error) {
	rows, err := q.db.Query(ctx, listAllCertificates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Certificate{}
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.OrganizationID,
			&i.Iin,
			&i.Name,
			&i.Code,
			&i.PdfPath,
			&i.Status,
			&i.RevokedReason,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesByEvent = `-- name: ListCertificatesByEvent :many
SELECT id, event_id, organization_id, iin, name, code, pdf_path, status, revoked_reason, payload, created_at, updated_at FROM certificates
WHERE event_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCertificatesByEventParams struct {
	EventID int64 `json:"event_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListCertificatesByEvent(ctx context.Context, arg ListCertificatesByEventParams) ([]Certificate, error) {
	rows, err := q.db.Query(ctx, listCertificatesByEvent, arg.EventID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Certificate{}
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.OrganizationID,
			&i.Iin,
			&i.Name,
			&i.Code,
			&i.PdfPath,
			&i.Status,
			&i.RevokedReason,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesByIIN = `-- name: ListCertificatesByIIN :many
SELECT c.id, c.event_id, c.organization_id, c.iin, c.name, c.code, c.pdf_path, c.status, c.revoked_reason, c.payload, c.created_at, c.updated_at, e.title as event_title, o.name as org_name
FROM certificates c
JOIN events e ON e.id = c.event_id
LEFT JOIN organizations o ON o.id = c.organization_id
WHERE c.iin = $1 AND c.status = 'valid'
ORDER BY c.created_at DESC
`

type ListCertificatesByIINRow struct {
	ID             int64              `json:"id"`
	EventID        int64              `json:"event_id"`
	OrganizationID pgtype.Int8        `json:"organization_id"`
	Iin            pgtype.Text        `json:"iin"`
	Name           pgtype.Text        `json:"name"`
	Code           string             `json:"code"`
	PdfPath        pgtype.Text        `json:"pdf_path"`
	Status         pgtype.Text        `json:"status"`
	RevokedReason  pgtype.Text        `json:"revoked_reason"`
	Payload        []byte             `json:"payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	EventTitle     string             `json:"event_title"`
	OrgName        pgtype.Text        `json:"org_name"`
}

func (q *Queries) ListCertificatesByIIN(ctx context.Context, iin pgtype.Text) ([]ListCertificatesByIINRow, error) {
	rows, err := q.db.Query(ctx, listCertificatesByIIN, iin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatesByIINRow{}
	for rows.Next() {
		var i ListCertificatesByIINRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.OrganizationID,
			&i.Iin,
			&i.Name,
			&i.Code,
			&i.PdfPath,
			&i.Status,
			&i.RevokedReason,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventTitle,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesByOrganization = `-- name: ListCertificatesByOrganization :many
SELECT id, event_id, organization_id, iin, name, code, pdf_path, status, revoked_reason, payload, created_at, updated_at FROM certificates
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCertificatesByOrganizationParams struct {
	OrganizationID pgtype.Int8 `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListCertificatesByOrganization(ctx context.Context, arg ListCertificatesByOrganizationParams) ([]Certificate, error) {
	rows, err := q.db.Query(ctx, listCertificatesByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Certificate{}
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.OrganizationID,
			&i.Iin,
			&i.Name,
			&i.Code,
			&i.PdfPath,
			&i.Status,
			&i.RevokedReason,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesByUserID = `-- name: ListCertificatesByUserID :many
SELECT c.id, c.event_id, c.organization_id, c.iin, c.name, c.code, c.pdf_path, c.status, c.revoked_reason, c.payload, c.created_at, c.updated_at, e.title as event_title, o.name as org_name
FROM certificates c
JOIN events e ON e.id = c.event_id
LEFT JOIN organizations o ON o.id = c.organization_id
WHERE c.iin = (SELECT users.iin FROM users WHERE users.id = $1 AND users.iin IS NOT NULL AND users.iin != '')
ORDER BY c.created_at DESC
`

type ListCertificatesByUserIDRow struct {
	ID             int64              `json:"id"`
	EventID        int64              `json:"event_id"`
	OrganizationID pgtype.Int8        `json:"organization_id"`
	Iin            pgtype.Text        `json:"iin"`
	Name           pgtype.Text        `json:"name"`
	Code           string             `json:"code"`
	PdfPath        pgtype.Text        `json:"pdf_path"`
	Status         pgtype.Text        `json:"status"`
	RevokedReason  pgtype.Text        `json:"revoked_reason"`
	Payload        []byte             `json:"payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	EventTitle     string             `json:"event_title"`
	OrgName        pgtype.Text        `json:"org_name"`
}

func (q *Queries) ListCertificatesByUserID(ctx context.Context, id int64) ([]ListCertificatesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listCertificatesByUserID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatesByUserIDRow{}
	for rows.Next() {
		var i ListCertificatesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.OrganizationID,
			&i.Iin,
			&i.Name,
			&i.Code,
			&i.PdfPath,
			&i.Status,
			&i.RevokedReason,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventTitle,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesForTeacher = `-- name: ListCertificatesForTeacher :many
SELECT c.id, c.event_id, c.organization_id, c.iin, c.name, c.code, c.pdf_path, c.status, c.revoked_reason, c.payload, c.created_at, c.updated_at, e.title as event_title, o.name as org_name
FROM certificates c
JOIN events e ON e.id = c.event_id
LEFT JOIN organizations o ON o.id = c.organization_id
WHERE c.iin IN (
  SELECT ts.student_iin FROM teacher_students ts WHERE ts.teacher_id = $1
  UNION
  SELECT u.iin FROM users u WHERE u.id = $1 AND u.iin IS NOT NULL AND u.iin != ''
)
ORDER BY c.created_at DESC
`

type ListCertificatesForTeacherRow struct {
	ID             int64              `json:"id"`
	EventID        int64              `json:"event_id"`
	OrganizationID pgtype.Int8        `json:"organization_id"`
	Iin            pgtype.Text        `json:"iin"`
	Name           pgtype.Text        `json:"name"`
	Code           string             `json:"code"`
	PdfPath        pgtype.Text        `json:"pdf_path"`
	Status         pgtype.Text        `json:"status"`
	RevokedReason  pgtype.Text        `json:"revoked_reason"`
	Payload        []byte             `json:"payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	EventTitle     string             `json:"event_title"`
	OrgName        pgtype.Text        `json:"org_name"`
}

func (q *Queries) ListCertificatesForTeacher(ctx context.Context, teacherID int64) ([]ListCertificatesForTeacherRow, error) {
	rows, err := q.db.Query(ctx, listCertificatesForTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatesForTeacherRow{}
	for rows.Next() {
		var i ListCertificatesForTeacherRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.OrganizationID,
			&i.Iin,
			&i.Name,
			&i.Code,
			&i.PdfPath,
			&i.Status,
			&i.RevokedReason,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventTitle,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCertificatesByIIN = `-- name: SearchCertificatesByIIN :many
SELECT c.id, c.event_id, c.iin, c.name, c.code, c.status, c.created_at,
       e.title as event_title, o.name as org_name
FROM certificates c
JOIN events e ON e.id = c.event_id
LEFT JOIN organizations o ON o.id = c.organization_id
WHERE c.iin = $1
ORDER BY c.created_at DESC
`

type SearchCertificatesByIINRow struct {
	ID         int64              `json:"id"`
	EventID    int64              `json:"event_id"`
	Iin        pgtype.Text        `json:"iin"`
	Name       pgtype.Text        `json:"name"`
	Code       string             `json:"code"`
	Status     pgtype.Text        `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	EventTitle string             `json:"event_title"`
	OrgName    pgtype.Text        `json:"org_name"`
}

func (q *Queries) SearchCertificatesByIIN(ctx context.Context, iin pgtype.Text) ([]SearchCertificatesByIINRow, error) {
	rows, err := q.db.Query(ctx, searchCertificatesByIIN, iin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCertificatesByIINRow{}
	for rows.Next() {
		var i SearchCertificatesByIINRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Iin,
			&i.Name,
			&i.Code,
			&i.Status,
			&i.CreatedAt,
			&i.EventTitle,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCertificateStatus = `-- name: UpdateCertificateStatus :one
UPDATE certificates
SET status = $2, revoked_reason = $3, updated_at = now()
WHERE id = $1
RETURNING id, event_id, organization_id, iin, name, code, pdf_path, status, revoked_reason, payload, created_at, updated_at
`

type UpdateCertificateStatusParams struct {
	ID            int64       `json:"id"`
	Status        pgtype.Text `json:"status"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) UpdateCertificateStatus(ctx context.Context, arg UpdateCertificateStatusParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, updateCertificateStatus, arg.ID, arg.Status, arg.RevokedReason)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.OrganizationID,
		&i.Iin,
		&i.Name,
		&i.Code,
		&i.PdfPath,
		&i.Status,
		&i.RevokedReason,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
