// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllEvents = `-- name: CountAllEvents :one
SELECT count(*) FROM events
`

func (q *Queries) CountAllEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsByOrganization = `-- name: CountEventsByOrganization :one
SELECT count(*) FROM events WHERE organization_id = $1
`

func (q *Queries) CountEventsByOrganization(ctx context.Context, organizationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByOrganization, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (organization_id, created_by, title, date, city, description, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, created_by, title, date, city, description, status, created_at, updated_at
`

type CreateEventParams struct {
	OrganizationID int64       `json:"organization_id"`
	CreatedBy      pgtype.Int8 `json:"created_by"`
	Title          string      `json:"title"`
	Date           pgtype.Date `json:"date"`
	City           pgtype.Text `json:"city"`
	Description    pgtype.Text `json:"description"`
	Status         pgtype.Text `json:"status"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.OrganizationID,
		arg.CreatedBy,
		arg.Title,
		arg.Date,
		arg.City,
		arg.Description,
		arg.Status,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Title,
		&i.Date,
		&i.City,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, organization_id, created_by, title, date, city, description, status, created_at, updated_at FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Title,
		&i.Date,
		&i.City,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllEvents = `-- name: ListAllEvents :many
SELECT id, organization_id, created_by, title, date, city, description, status, created_at, updated_at FROM events
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllEvents(ctx context.Context, arg ListAllEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listAllEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Title,
			&i.Date,
			&i.City,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByOrganization = `-- name: ListEventsByOrganization :many
SELECT id, organization_id, created_by, title, date, city, description, status, created_at, updated_at FROM events
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEventsByOrganizationParams struct {
	OrganizationID int64 `json:"organization_id"`
	Limit          int32 `json:"limit"`
	Offset         int32 `json:"offset"`
}

func (q *Queries) ListEventsByOrganization(ctx context.Context, arg ListEventsByOrganizationParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Title,
			&i.Date,
			&i.City,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = COALESCE($1, title),
    date = COALESCE($2, date),
    city = COALESCE($3, city),
    description = COALESCE($4, description),
    status = COALESCE($5, status),
    updated_at = now()
WHERE id = $6
RETURNING id, organization_id, created_by, title, date, city, description, status, created_at, updated_at
`

type UpdateEventParams struct {
	Title       pgtype.Text `json:"title"`
	Date        pgtype.Date `json:"date"`
	City        pgtype.Text `json:"city"`
	Description pgtype.Text `json:"description"`
	Status      pgtype.Text `json:"status"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.Title,
		arg.Date,
		arg.City,
		arg.Description,
		arg.Status,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Title,
		&i.Date,
		&i.City,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
