// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: health.sql

package sqlcdb

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :one
SELECT 1 AS ok
`

func (q *Queries) HealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
