// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         int64              `json:"id"`
	ActorID    pgtype.Int8        `json:"actor_id"`
	Action     string             `json:"action"`
	ObjectType pgtype.Text        `json:"object_type"`
	ObjectID   pgtype.Text        `json:"object_id"`
	Meta       []byte             `json:"meta"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Certificate struct {
	ID             int64              `json:"id"`
	EventID        int64              `json:"event_id"`
	OrganizationID pgtype.Int8        `json:"organization_id"`
	Iin            pgtype.Text        `json:"iin"`
	Name           pgtype.Text        `json:"name"`
	Code           string             `json:"code"`
	PdfPath        pgtype.Text        `json:"pdf_path"`
	Status         pgtype.Text        `json:"status"`
	RevokedReason  pgtype.Text        `json:"revoked_reason"`
	Payload        []byte             `json:"payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID             int64              `json:"id"`
	OrganizationID int64              `json:"organization_id"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	Title          string             `json:"title"`
	Date           pgtype.Date        `json:"date"`
	City           pgtype.Text        `json:"city"`
	Description    pgtype.Text        `json:"description"`
	Status         pgtype.Text        `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ImportBatch struct {
	ID         int64              `json:"id"`
	EventID    int64              `json:"event_id"`
	FilePath   string             `json:"file_path"`
	Status     pgtype.Text        `json:"status"`
	RowsTotal  pgtype.Int4        `json:"rows_total"`
	RowsOk     pgtype.Int4        `json:"rows_ok"`
	RowsFailed pgtype.Int4        `json:"rows_failed"`
	Mapping    []byte             `json:"mapping"`
	Tokens     []byte             `json:"tokens"`
	Report     []byte             `json:"report"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Organization struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Domain    pgtype.Text        `json:"domain"`
	LogoPath  pgtype.Text        `json:"logo_path"`
	Status    pgtype.Text        `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationMember struct {
	ID             int64              `json:"id"`
	OrganizationID int64              `json:"organization_id"`
	UserID         int64              `json:"user_id"`
	Role           pgtype.Text        `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ParticipantRow struct {
	ID        int64              `json:"id"`
	BatchID   int64              `json:"batch_id"`
	Iin       pgtype.Text        `json:"iin"`
	Name      pgtype.Text        `json:"name"`
	Payload   []byte             `json:"payload"`
	Status    pgtype.Text        `json:"status"`
	Error     pgtype.Text        `json:"error"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TeacherStudent struct {
	ID         int64              `json:"id"`
	TeacherID  int64              `json:"teacher_id"`
	StudentIin string             `json:"student_iin"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Template struct {
	ID        int64              `json:"id"`
	EventID   int64              `json:"event_id"`
	FilePath  string             `json:"file_path"`
	Tokens    []byte             `json:"tokens"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	Email     pgtype.Text        `json:"email"`
	Password  string             `json:"password"`
	Iin       pgtype.Text        `json:"iin"`
	Role      string             `json:"role"`
	IsActive  pgtype.Bool        `json:"is_active"`
	Language  pgtype.Text        `json:"language"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
