// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrganizationMember = `-- name: AddOrganizationMember :one
INSERT INTO organization_members (organization_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, organization_id, user_id, role, created_at
`

type AddOrganizationMemberParams struct {
	OrganizationID int64       `json:"organization_id"`
	UserID         int64       `json:"user_id"`
	Role           pgtype.Text `json:"role"`
}

func (q *Queries) AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, addOrganizationMember, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const countOrganizations = `-- name: CountOrganizations :one
SELECT count(*) FROM organizations
`

func (q *Queries) CountOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, domain, logo_path, status)
VALUES ($1, $2, $3, $4)
RETURNING id, name, domain, logo_path, status, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name     string      `json:"name"`
	Domain   pgtype.Text `json:"domain"`
	LogoPath pgtype.Text `json:"logo_path"`
	Status   pgtype.Text `json:"status"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.Domain,
		arg.LogoPath,
		arg.Status,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.LogoPath,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, domain, logo_path, status, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.LogoPath,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationMember = `-- name: GetOrganizationMember :one
SELECT id, organization_id, user_id, role, created_at FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type GetOrganizationMemberParams struct {
	OrganizationID int64 `json:"organization_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) GetOrganizationMember(ctx context.Context, arg GetOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMember, arg.OrganizationID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserOrganization = `-- name: GetUserOrganization :one
SELECT o.id, o.name, o.domain, o.logo_path, o.status, o.created_at, o.updated_at FROM organizations o
JOIN organization_members om ON om.organization_id = o.id
WHERE om.user_id = $1
LIMIT 1
`

func (q *Queries) GetUserOrganization(ctx context.Context, userID int64) (Organization, error) {
	row := q.db.QueryRow(ctx, getUserOrganization, userID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.LogoPath,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT om.id, om.organization_id, om.user_id, om.role, om.created_at,
       u.username, u.email
FROM organization_members om
JOIN users u ON u.id = om.user_id
WHERE om.organization_id = $1
ORDER BY om.created_at DESC
`

type ListOrganizationMembersRow struct {
	ID             int64              `json:"id"`
	OrganizationID int64              `json:"organization_id"`
	UserID         int64              `json:"user_id"`
	Role           pgtype.Text        `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Username       string             `json:"username"`
	Email          pgtype.Text        `json:"email"`
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, organizationID int64) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembersRow{}
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, domain, logo_path, status, created_at, updated_at FROM organizations
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListOrganizationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.LogoPath,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrganizationMember = `-- name: RemoveOrganizationMember :exec
DELETE FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type RemoveOrganizationMemberParams struct {
	OrganizationID int64 `json:"organization_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) RemoveOrganizationMember(ctx context.Context, arg RemoveOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, removeOrganizationMember, arg.OrganizationID, arg.UserID)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET name = COALESCE($1, name),
    domain = COALESCE($2, domain),
    logo_path = COALESCE($3, logo_path),
    status = COALESCE($4, status),
    updated_at = now()
WHERE id = $5
RETURNING id, name, domain, logo_path, status, created_at, updated_at
`

type UpdateOrganizationParams struct {
	Name     pgtype.Text `json:"name"`
	Domain   pgtype.Text `json:"domain"`
	LogoPath pgtype.Text `json:"logo_path"`
	Status   pgtype.Text `json:"status"`
	ID       int64       `json:"id"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.Name,
		arg.Domain,
		arg.LogoPath,
		arg.Status,
		arg.ID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.LogoPath,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
