// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package sqlcdb

import (
	"context"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (event_id, file_path, tokens)
VALUES ($1, $2, $3)
RETURNING id, event_id, file_path, tokens, created_at
`

type CreateTemplateParams struct {
	EventID  int64  `json:"event_id"`
	FilePath string `json:"file_path"`
	Tokens   []byte `json:"tokens"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate, arg.EventID, arg.FilePath, arg.Tokens)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.FilePath,
		&i.Tokens,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTemplatesByEventID = `-- name: DeleteTemplatesByEventID :exec
DELETE FROM templates WHERE event_id = $1
`

func (q *Queries) DeleteTemplatesByEventID(ctx context.Context, eventID int64) error {
	_, err := q.db.Exec(ctx, deleteTemplatesByEventID, eventID)
	return err
}

const getTemplateByEventID = `-- name: GetTemplateByEventID :one
SELECT id, event_id, file_path, tokens, created_at FROM templates
WHERE event_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetTemplateByEventID(ctx context.Context, eventID int64) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByEventID, eventID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.FilePath,
		&i.Tokens,
		&i.CreatedAt,
	)
	return i, err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, event_id, file_path, tokens, created_at FROM templates WHERE id = $1
`

func (q *Queries) GetTemplateByID(ctx context.Context, id int64) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.FilePath,
		&i.Tokens,
		&i.CreatedAt,
	)
	return i, err
}
