// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeacherStudent = `-- name: AddTeacherStudent :one
INSERT INTO teacher_students (teacher_id, student_iin)
VALUES ($1, $2)
RETURNING id, teacher_id, student_iin, created_at
`

type AddTeacherStudentParams struct {
	TeacherID  int64  `json:"teacher_id"`
	StudentIin string `json:"student_iin"`
}

func (q *Queries) AddTeacherStudent(ctx context.Context, arg AddTeacherStudentParams) (TeacherStudent, error) {
	row := q.db.QueryRow(ctx, addTeacherStudent, arg.TeacherID, arg.StudentIin)
	var i TeacherStudent
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.StudentIin,
		&i.CreatedAt,
	)
	return i, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password, iin, role, language)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, email, password, iin, role, is_active, language, created_at, updated_at
`

type CreateUserParams struct {
	Username string      `json:"username"`
	Email    pgtype.Text `json:"email"`
	Password string      `json:"password"`
	Iin      pgtype.Text `json:"iin"`
	Role     string      `json:"role"`
	Language pgtype.Text `json:"language"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Iin,
		arg.Role,
		arg.Language,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Iin,
		&i.Role,
		&i.IsActive,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) EmailExists(ctx context.Context, email pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, iin, role, is_active, language, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Iin,
		&i.Role,
		&i.IsActive,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password, iin, role, is_active, language, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Iin,
		&i.Role,
		&i.IsActive,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIIN = `-- name: GetUserByIIN :one
SELECT id, username, email, password, iin, role, is_active, language, created_at, updated_at
FROM users
WHERE iin = $1
`

func (q *Queries) GetUserByIIN(ctx context.Context, iin pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIIN, iin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Iin,
		&i.Role,
		&i.IsActive,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, iin, role, is_active, language, created_at, updated_at
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Iin,
		&i.Role,
		&i.IsActive,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeacherStudents = `-- name: ListTeacherStudents :many
SELECT id, teacher_id, student_iin, created_at
FROM teacher_students
WHERE teacher_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTeacherStudents(ctx context.Context, teacherID int64) ([]TeacherStudent, error) {
	rows, err := q.db.Query(ctx, listTeacherStudents, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeacherStudent{}
	for rows.Next() {
		var i TeacherStudent
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.StudentIin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, iin, role, is_active, language, created_at, updated_at
FROM users
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	Email     pgtype.Text        `json:"email"`
	Iin       pgtype.Text        `json:"iin"`
	Role      string             `json:"role"`
	IsActive  pgtype.Bool        `json:"is_active"`
	Language  pgtype.Text        `json:"language"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Iin,
			&i.Role,
			&i.IsActive,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeacherStudent = `-- name: RemoveTeacherStudent :exec
DELETE FROM teacher_students
WHERE teacher_id = $1 AND student_iin = $2
`

type RemoveTeacherStudentParams struct {
	TeacherID  int64  `json:"teacher_id"`
	StudentIin string `json:"student_iin"`
}

func (q *Queries) RemoveTeacherStudent(ctx context.Context, arg RemoveTeacherStudentParams) error {
	_, err := q.db.Exec(ctx, removeTeacherStudent, arg.TeacherID, arg.StudentIin)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password = $2, updated_at = now() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       int64  `json:"id"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET email = COALESCE($1, email),
    iin = COALESCE($2, iin),
    language = COALESCE($3, language),
    updated_at = now()
WHERE id = $4
RETURNING id, username, email, iin, role, is_active, language, created_at, updated_at
`

type UpdateUserProfileParams struct {
	Email    pgtype.Text `json:"email"`
	Iin      pgtype.Text `json:"iin"`
	Language pgtype.Text `json:"language"`
	ID       int64       `json:"id"`
}

type UpdateUserProfileRow struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	Email     pgtype.Text        `json:"email"`
	Iin       pgtype.Text        `json:"iin"`
	Role      string             `json:"role"`
	IsActive  pgtype.Bool        `json:"is_active"`
	Language  pgtype.Text        `json:"language"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.Email,
		arg.Iin,
		arg.Language,
		arg.ID,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Iin,
		&i.Role,
		&i.IsActive,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
