---
- name: Install Nginx
  dnf:
    name: nginx
    state: present

- name: Deploy Nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/jetistik.conf
    mode: "0644"
  notify: Reload Nginx

- name: Remove default Nginx server block
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: Reload Nginx

- name: Start and enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: true

- name: Allow Nginx to connect to upstream (SELinux)
  seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  ignore_errors: true
